<a href="https://colab.research.google.com/github/mrtlckn/IntroToPytorch/blob/main/3_TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
###

my_torch21 = torch.arange(15)
my_torch21 = my_torch21.reshape(-1, 5)
my_torch21

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [16]:
### View

my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Differences between shape and view

-----

In [24]:
# with reshape and view, they will update

# make a change to the original tensor with reshape and view that change will get reflected
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_torch6 # it has been updated


tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slices

In [28]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [32]:
# Grap slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [33]:
my_torch8[:,1] # up until the 1th column

tensor([1, 3, 5, 7, 9])

In [34]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])