<a href="https://colab.research.google.com/github/mrtlckn/IntroToPytorch/blob/main/4_TensorMath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math Operations


*   Add, Substract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassingment



In [29]:
import torch
import numpy as np

In [30]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

#### Addition

In [31]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [32]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

----

#### Substraction

In [33]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [34]:
# Subs Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

-----

#### Multiplication

In [35]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [36]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

-----

#### Division

In [37]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [38]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

-----

#### Remainder Modules

In [39]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [40]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

-----


#### Exponents / Power

In [41]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

----


####  Another way to write longhand

In [42]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

#### Reassingment


In [43]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [44]:
tensor_a

tensor([1, 2, 3, 4])

In [45]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)


tensor([ 6,  8, 10, 12])

In [46]:
print(tensor_a)

tensor([ 6,  8, 10, 12])
