<a href="https://colab.research.google.com/github/mrtlckn/IntroToPytorch/blob/main/IntroToPytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import torch

In [ ]:
!pip list

# Tensors

* A torch.Tensor is a multi-dimensional matrix containing elements of a single
data type.
* Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
* default data type of float32.
* More suitable for deep learning than a numpy array.

In [4]:
import torch
import numpy as np

# LISTS


In [6]:
my_list = [1,2,3,4,5] #One dimension array
print(my_list)

my_list2 = [[1,2,3,4,5], [6,7,8,9,10]] # multi-dimensional array
print(my_list2)

[1, 2, 3, 4, 5]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


# Numpy Arrays

In [7]:
np1 = np.random.rand(3,4) # 3 rows, 4 columns
print(np1)

[[0.38694634 0.84325422 0.55635368 0.47121562]
 [0.24634688 0.61324398 0.53375782 0.50818388]
 [0.90786444 0.13431138 0.39299357 0.05912267]]


In [8]:
np1.dtype

dtype('float64')

# TENSORS

In [10]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)

tensor([[ 1.5727, -0.8215, -0.6959, -1.2747],
        [ 1.0509,  1.0361,  0.7985,  1.4154],
        [ 0.8185, -1.3412,  0.0177, -0.6828]])


In [14]:
tensor_3d = torch.zeros(2,3,4) #2 matrix. Each matrix has 3 rows, 4 columns
print(tensor_3d)


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [16]:
# Create tensor out of numpy array

my_tensor = torch.tensor(np1)
print(my_tensor)

tensor([[0.3869, 0.8433, 0.5564, 0.4712],
        [0.2463, 0.6132, 0.5338, 0.5082],
        [0.9079, 0.1343, 0.3930, 0.0591]], dtype=torch.float64)


In [20]:
print(my_tensor.dtype) #float64 because converted from numpy array to Tensor
print(tensor_2d.dtype)

# Tensors by default are float32 but we can easily change

torch.float64
torch.float32
